### ISSUE TITLE
before on Facade::wrapPDO() : Preload mode requires that you call Core::preload 

### ISSUE THREAD

**Issue by AnnoyingTechnology** [Moxio/sqlite-extended-api#6]
When trying to wrap a PDO instance, I get `Preload mode requires that you call Core::preload before`

Any pointers on how to solve that ?
On `PHP 8.0.19 `

Thanks

**Comment by aboks** [comment]
I've only used this library over the CLI myself, never with a webserver, so I've never used it with preloading mode. The error you see comes from the underlying Z-Engine library. Its readme contains information about how to use it in preloading mode: https://github.com/lisachenko/z-engine#pre-requisites-and-initialization. I hope that gives you enough pointers to get this working.
